from __future__ import annotations

from src.localization import normalize_language

_TEXTS: dict[str, dict[str, str]] = {
    "en": {
        "menu_signals": "Signals",
        "menu_watchlists": "Favorites",
        "menu_delivery": "Alerts",
        "menu_stats": "Results",
        "menu_settings_premium": "Settings",
        "menu_ai_tools": "AI Coin Analysis",
        "menu_setup_wizard": "Quick Setup",
        "menu_daily_recap": "Day Results",
        "menu_weekly_recap": "Week Results",
        "menu_control_center": "Results Center",
        "menu_compare": "What Changed",
        "menu_themes": "Sets",
        "menu_save_theme": "Create Set",
        "menu_add_to_theme": "Add Coin",
        "menu_rename_theme": "Rename",
        "menu_delete_theme": "Delete",
        "menu_all_symbols_scope": "All Coins",
        "menu_delivery_edit": "Change Alerts",
        "menu_resume_now": "Resume Alerts",
        "menu_open_latest": "Fresh Signals",
        "menu_open_strongest": "Strongest Now",
        "menu_open_stats": "Open Results",
        "menu_stay_digest": "Stay in Digest",
        "menu_start_signals": "Start Receiving Signals",
        "menu_edit_watchlist": "Edit Favorites",
        "menu_gold_card": "Open XAUUSD Card",
        "menu_gold_link": "TradingView XAUUSD",
        "menu_gold_alerts_on": "Gold Alerts: ON",
        "menu_gold_alerts_off": "Gold Alerts: OFF",
        "delivery_mode_instant": "Live Alerts",
        "delivery_mode_digest": "1h Summary",
        "delivery_mode_quiet": "Quiet Mode",
        "snooze_1h": "Pause 1h",
        "snooze_8h": "Pause 8h",
        "snooze_tomorrow": "Until Morning",
        "snooze_today": "Until Tonight",
        "quiet_hours_off": "Night: ON",
        "quiet_hours_late": "Night: OFF 23:00-07:00",
        "quiet_hours_overnight": "Night: OFF 00:00-08:00",
        "theme_majors": "Top Coins",
        "theme_memes": "Meme Coins",
        "theme_gold": "Gold",
        "theme_custom": "Favorites",
        "scope_all_coins": "All coins",
        "scope_favorites": "Favorites only",
        "scope_set": "Set only: {theme}",
        "scope_set_short": "Set: {theme}",
        "hub_signals_title": "Signals",
        "hub_signals_body": "📈 Open fresh signals, strongest setups, or check any ticker by hand.",
        "hub_watchlists_title": "Favorites",
        "hub_watchlists_body": "⭐ Keep your favorites separate, save reusable sets, and switch what the bot tracks in one tap.",
        "hub_delivery_title": "Alerts",
        "hub_delivery_body": "📬 Choose between live alerts, a 1h summary, night mute, and quick pauses.",
        "hub_stats_title": "Results",
        "hub_stats_body": "📊 See day and week results plus a quick snapshot of your activity.",
        "hub_ai_title": "AI Coin Analysis",
        "hub_ai_body": "🤖 Type any coin, choose a timeframe, and get an AI explanation for the chart right now.",
        "hub_settings_title": "Settings",
        "hub_settings_body": "⚙️ Guided setup, filters, language, and the core bot preferences.",
        "hub_gold_title": "Gold",
        "hub_gold_body": "🪙 Keep XAUUSD in its own tab: fresh card, alert toggle, and one clean chart link.",
        "delivery_status_live": "Alerts are active now.",
        "delivery_status_paused": "Paused until {timestamp}",
        "delivery_status_quiet_hours": "Night alerts are off right now: {window}",
        "delivery_status_mode": "How alerts arrive: {mode}",
        "delivery_status_followups": "Results after alerts: {state}",
        "delivery_status_gold": "Gold alerts: {state}",
        "delivery_status_quiet": "Night alerts: {window}",
        "delivery_status_resume": "Resume summaries are active.",
        "delivery_state_on": "ON",
        "delivery_state_off": "OFF",
        "delivery_center_intro": "Choose how alerts arrive, whether follow-ups are enabled, and if night alerts should stay on.",
        "control_center_title": "Results Center",
        "control_center_activity": "Recent Activity",
        "control_center_delivery": "Alerts",
        "control_center_setup": "Setup",
        "control_center_top": "Top Signals",
        "control_center_watchlist": "Favorites",
        "control_center_today": "Today",
        "control_center_week": "7d",
        "control_center_month": "30d",
        "control_center_none": "No delivered cards yet.",
        "digest_title": "1h Summary",
        "digest_empty": "Nothing meaningful matched your setup in the last hour.",
        "digest_watchlist_hits": "My list hits",
        "digest_followups": "Important follow-ups",
        "digest_strongest": "Strongest setups",
        "resume_title": "You're Back",
        "resume_empty": "Nothing meaningful moved while delivery was quiet.",
        "daily_recap_title": "Results for Today",
        "weekly_recap_title": "Results for the Week",
        "recap_empty": "Nothing important cleared your current filters in this period.",
        "daily_recap_empty": "No strong follow-up results yet for today.",
        "recap_best_followups": "Best follow-up winners",
        "recap_recent_alerts": "Recent delivered signals",
        "recap_no_deliveries": "No signals were delivered to you in this period yet.",
        "recap_waiting_followups": "Signals were delivered, but there are no strong follow-up winners yet.",
        "recap_delivered_alerts": "Delivered signals in this period",
        "recap_based_on_delivered": "Only follow-up outcomes from signals delivered to you in this period are shown here.",
        "onboarding_title": "Desk Setup",
        "onboarding_progress": "Step {current}/{total}",
        "onboarding_language": "Choose the language for menus and cards.",
        "onboarding_style": "Pick the signal style you want by default.",
        "onboarding_direction": "Which side should be prioritized?",
        "onboarding_symbols": "Add favorite symbols. You can tap suggestions or send a short list like BTC, ETH, SOL.",
        "onboarding_symbols_empty": "No favorites yet. You can keep the full market for now.",
        "onboarding_universe": "Should delivery use the whole market or only your watchlist?",
        "onboarding_delivery": "Choose how alerts should reach you.",
        "onboarding_followups": "Do you want staged follow-ups after delivered alerts?",
        "onboarding_gold": "Include gold in the same flow?",
        "onboarding_quiet_hours": "Pick quiet hours for nights or downtime.",
        "onboarding_summary": "Your setup is ready.",
        "onboarding_skip": "Skip",
        "onboarding_done": "Done",
        "onboarding_add_more": "Add More",
        "onboarding_clear": "Clear",
        "onboarding_use_suggestions": "Use Suggestions",
        "onboarding_restart": "Re-run Setup",
        "onboarding_saved": "Setup saved.",
        "watchlists_title": "Favorites",
        "watchlists_themes_title": "Sets",
        "watchlists_themes_body": "🎨 Save reusable sets, add coins directly into them, and switch tracking without touching your favorites.",
        "watchlists_theme_active": "Current set: {theme}",
        "watchlists_theme_saved": "Set saved: {theme}",
        "watchlists_theme_renamed": "Set renamed: {theme}",
        "watchlists_theme_deleted": "Set deleted: {theme}",
        "watchlists_theme_missing": "Set not found.",
        "watchlists_prompt_save": "Send a short name for the current set.",
        "watchlists_prompt_rename": "Send the new set name.",
        "watchlists_prompt_delete": "Deleting the selected set...",
        "watchlists_prompt_add": "Send one or more tickers to add into the set: {theme}. Example: BTC, ETH, SOL",
        "watchlists_prompt_invalid": "That name is not valid. Keep it short and clear.",
        "watchlists_symbols_added": "Added to set {theme}: {symbols}",
        "watchlists_builtin_note": "If you edit a tracked set manually, it turns into your own favorites list.",
        "watchlists_center_intro": "This is where your favorites live and where you manage reusable sets for tracking.",
        "gold_center_title": "Gold / XAUUSD",
        "gold_center_intro": "A separate gold tab so XAUUSD does not get lost between crypto screens.",
        "gold_center_same_chart": "Chart style: same live card format as crypto",
        "gold_center_external": "External chart: {label}",
        "gold_center_alerts": "Gold alerts: {state}",
        "gold_center_hint": "Use the buttons below for a fresh XAUUSD card, TradingView, or the gold alert toggle.",
        "gold_weekend_note": "Gold is closed for the weekend. This card shows the last closed session. Live trading resumes Monday, {date}.",
        "gold_weekend_fallback": "Gold is closed for the weekend. Live trading resumes Monday, {date}. The last closed gold card could not be loaded right now.",
        "compare_title": "What Changed",
        "compare_empty": "No useful comparison point is available yet.",
        "compare_vs_original": "vs original signal",
        "compare_vs_symbol": "vs previous {symbol} setup",
        "compare_vs_recent": "vs last delivered setup",
        "compare_passed": "Why it passed your filters",
        "compare_changed": "What changed",
        "compare_strength": "Relative strength",
        "compare_stronger": "Stronger than the reference setup",
        "compare_weaker": "Weaker than the reference setup",
        "compare_similar": "Close to the reference setup",
        "compare_filter_score": "Score cleared your floor: {value}",
        "compare_filter_volume": "Volume cleared your floor: {value}",
        "compare_filter_direction": "Direction matched your filter: {value}",
        "compare_filter_watchlist": "It hit your current coin list",
        "compare_filter_gold": "Gold is enabled in your delivery flow",
        "compare_change_score_up": "Score is higher by {value}",
        "compare_change_score_down": "Score is lower by {value}",
        "compare_change_score_flat": "Score is unchanged",
        "compare_change_rsi": "RSI moved from {previous} to {current}",
        "compare_change_volume_up": "24h volume is stronger",
        "compare_change_volume_down": "24h volume is lighter",
        "compare_change_volume_flat": "24h volume is about the same",
        "compare_change_timeframe": "Timeframe changed from {previous} to {current}",
        "compare_change_direction": "Direction changed from {previous} to {current}",
    },
    "ru": {
        "menu_signals": "Сигналы",
        "menu_watchlists": "Избранные",
        "menu_delivery": "Уведомления",
        "menu_stats": "Итоги",
        "menu_settings_premium": "Настройки",
        "menu_ai_tools": "AI анализ монеты",
        "menu_setup_wizard": "Быстрая настройка",
        "menu_daily_recap": "Результаты за день",
        "menu_weekly_recap": "Результаты за неделю",
        "menu_control_center": "Центр итогов",
        "menu_compare": "Что изменилось",
        "menu_themes": "Наборы",
        "menu_save_theme": "Создать набор",
        "menu_add_to_theme": "Добавить монету",
        "menu_rename_theme": "Переименовать",
        "menu_delete_theme": "Удалить",
        "menu_all_symbols_scope": "Все монеты",
        "menu_delivery_edit": "Изменить уведомления",
        "menu_resume_now": "Возобновить уведомления",
        "menu_open_latest": "Свежие сигналы",
        "menu_open_strongest": "Самые сильные сейчас",
        "menu_open_stats": "Открыть итоги",
        "menu_stay_digest": "Остаться в дайджесте",
        "menu_start_signals": "Начать получать сигналы",
        "menu_edit_watchlist": "Изменить избранные",
        "menu_gold_card": "Открыть XAUUSD",
        "menu_gold_link": "TradingView XAUUSD",
        "menu_gold_alerts_on": "Золото: ВКЛ",
        "menu_gold_alerts_off": "Золото: ВЫКЛ",
        "delivery_mode_instant": "Сигналы сразу",
        "delivery_mode_digest": "Сводка за час",
        "delivery_mode_quiet": "Тихий режим",
        "snooze_1h": "Пауза 1ч",
        "snooze_8h": "Пауза 8ч",
        "snooze_tomorrow": "До утра",
        "snooze_today": "До конца дня",
        "quiet_hours_off": "Ночь: ВКЛ",
        "quiet_hours_late": "Ночь: ВЫКЛ 23:00-07:00",
        "quiet_hours_overnight": "Ночь: ВЫКЛ 00:00-08:00",
        "theme_majors": "Топ монеты",
        "theme_memes": "Мем-монеты",
        "theme_gold": "Золото",
        "theme_custom": "Избранные",
        "scope_all_coins": "Все монеты",
        "scope_favorites": "Только избранные",
        "scope_set": "Только набор: {theme}",
        "scope_set_short": "Набор: {theme}",
        "hub_signals_title": "Сигналы",
        "hub_signals_body": "📈 Открой свежие сигналы, самые сильные сетапы или проверь любую монету вручную.",
        "hub_watchlists_title": "Избранные",
        "hub_watchlists_body": "⭐ Держи избранные отдельно, сохраняй готовые наборы и переключай отслеживание в один тап.",
        "hub_delivery_title": "Уведомления",
        "hub_delivery_body": "📬 Выбери, слать ли сигналы сразу, одной сводкой за час или молчать ночью и на паузе.",
        "hub_stats_title": "Итоги",
        "hub_stats_body": "📊 Результаты за день и неделю плюс короткая сводка по твоей активности.",
        "hub_ai_title": "AI анализ монеты",
        "hub_ai_body": "🤖 Напиши монету, выбери таймфрейм и получи AI-разбор графика на текущий момент.",
        "hub_settings_title": "Настройки",
        "hub_settings_body": "⚙️ Пошаговая настройка, фильтры сигналов, язык и основные параметры бота.",
        "hub_gold_title": "Золото",
        "hub_gold_body": "🪙 Отдельный раздел для XAUUSD: свежая карточка, переключатель уведомлений и нормальный график.",
        "delivery_status_live": "Сейчас сигналы приходят.",
        "delivery_status_paused": "Пауза до {timestamp}",
        "delivery_status_quiet_hours": "Ночные уведомления сейчас выключены: {window}",
        "delivery_status_mode": "Как приходят сигналы: {mode}",
        "delivery_status_followups": "Результаты после сигнала: {state}",
        "delivery_status_gold": "Уведомления по золоту: {state}",
        "delivery_status_quiet": "Ночные уведомления: {window}",
        "delivery_status_resume": "Итог после паузы включен.",
        "delivery_state_on": "ВКЛ",
        "delivery_state_off": "ВЫКЛ",
        "delivery_center_intro": "Здесь настраивается, как приходят сигналы, нужны ли follow-up и работают ли ночные уведомления.",
        "control_center_title": "Центр итогов",
        "control_center_activity": "Недавняя активность",
        "control_center_delivery": "Уведомления",
        "control_center_setup": "Настройка",
        "control_center_top": "Топ сигналы",
        "control_center_watchlist": "Избранные",
        "control_center_today": "Сегодня",
        "control_center_week": "7д",
        "control_center_month": "30д",
        "control_center_none": "Пока нет доставленных карточек.",
        "digest_title": "Сводка за час",
        "digest_empty": "За последний час не было ничего, что прошло бы твой текущий сетап.",
        "digest_watchlist_hits": "Попадания в список",
        "digest_followups": "Важные фоллоу-апы",
        "digest_strongest": "Самые сильные сетапы",
        "resume_title": "Ты снова в потоке",
        "resume_empty": "Пока доставка была тихой, ничего важного не произошло.",
        "daily_recap_title": "Результаты за день",
        "weekly_recap_title": "Результаты за неделю",
        "recap_empty": "За этот период ничего важного не прошло через твои текущие фильтры.",
        "daily_recap_empty": "Сегодня пока нет хороших follow-up результатов по твоим фильтрам.",
        "recap_best_followups": "Лучшие монеты в плюс по follow-up",
        "recap_recent_alerts": "Последние доставленные сигналы",
        "recap_no_deliveries": "За этот период тебе пока не было доставлено сигналов.",
        "recap_waiting_followups": "Сигналы были доставлены, но сильных follow-up победителей пока нет.",
        "recap_delivered_alerts": "Сигналов доставлено за период",
        "recap_based_on_delivered": "Здесь показаны только follow-up по тем сигналам, которые были отправлены именно тебе за этот период.",
        "onboarding_title": "Настройка Desk",
        "onboarding_progress": "Шаг {current}/{total}",
        "onboarding_language": "Выбери язык меню и карточек.",
        "onboarding_style": "Выбери базовый стиль потока сигналов.",
        "onboarding_direction": "Какую сторону приоритизировать?",
        "onboarding_symbols": "Добавь любимые тикеры. Можно нажать подсказки или отправить список вроде BTC, ETH, SOL.",
        "onboarding_symbols_empty": "Избранного пока нет. Можно оставить весь рынок и настроить позже.",
        "onboarding_universe": "Поток должен идти по всему рынку или только по watchlist?",
        "onboarding_delivery": "Выбери, как бот должен доставлять сигналы.",
        "onboarding_followups": "Нужны ли follow-up после доставленных алертов?",
        "onboarding_gold": "Включить золото в этот же поток?",
        "onboarding_quiet_hours": "Выбери quiet hours для ночи или паузы.",
        "onboarding_summary": "Настройка готова.",
        "onboarding_skip": "Пропустить",
        "onboarding_done": "Готово",
        "onboarding_add_more": "Добавить ещё",
        "onboarding_clear": "Очистить",
        "onboarding_use_suggestions": "Взять подсказки",
        "onboarding_restart": "Пройти заново",
        "onboarding_saved": "Настройка сохранена.",
        "watchlists_title": "Избранные",
        "watchlists_themes_title": "Наборы",
        "watchlists_themes_body": "🎨 Сохраняй наборы, добавляй в них монеты напрямую и быстро переключай отслеживание, не ломая избранные.",
        "watchlists_theme_active": "Текущий набор: {theme}",
        "watchlists_theme_saved": "Набор сохранён: {theme}",
        "watchlists_theme_renamed": "Набор переименован: {theme}",
        "watchlists_theme_deleted": "Набор удалён: {theme}",
        "watchlists_theme_missing": "Набор не найден.",
        "watchlists_prompt_save": "Отправь короткое название для текущего набора.",
        "watchlists_prompt_rename": "Отправь новое название набора.",
        "watchlists_prompt_delete": "Удаляю выбранный набор...",
        "watchlists_prompt_add": "Отправь один или несколько тикеров, чтобы добавить их в набор {theme}. Например: BTC, ETH, SOL",
        "watchlists_prompt_invalid": "Такое название не подходит. Сделай его коротким и понятным.",
        "watchlists_symbols_added": "В набор {theme} добавлено: {symbols}",
        "watchlists_builtin_note": "Если редактируешь активный набор вручную, он превращается в твои избранные.",
        "watchlists_center_intro": "Здесь живут твои избранные и все сохранённые наборы для быстрого переключения.",
        "gold_center_title": "Золото / XAUUSD",
        "gold_center_intro": "Отдельная вкладка по золоту, чтобы XAUUSD не терялся между криптоэкранами.",
        "gold_center_same_chart": "График: такая же живая карточка, как и у крипты",
        "gold_center_external": "Внешний график: {label}",
        "gold_center_alerts": "Уведомления по золоту: {state}",
        "gold_center_hint": "Ниже можно открыть свежую карточку XAUUSD, TradingView или включить и выключить золото.",
        "gold_weekend_note": "Золото сейчас закрыто на выходные. Эта карточка показывает последнюю закрытую сессию. Новая торговля начнется в понедельник, {date}.",
        "gold_weekend_fallback": "Золото сейчас закрыто на выходные. Новая торговля начнется в понедельник, {date}. Последнюю закрытую карточку золота сейчас не удалось загрузить.",
        "compare_title": "Что изменилось",
        "compare_empty": "Пока нет подходящей точки сравнения.",
        "compare_vs_original": "против исходного сигнала",
        "compare_vs_symbol": "против прошлого сетапа {symbol}",
        "compare_vs_recent": "против последнего доставленного кейса",
        "compare_passed": "Почему сигнал прошёл твои фильтры",
        "compare_changed": "Что изменилось",
        "compare_strength": "Относительная сила",
        "compare_stronger": "Сильнее, чем эталонный сетап",
        "compare_weaker": "Слабее, чем эталонный сетап",
        "compare_similar": "Почти на уровне эталонного сетапа",
        "compare_filter_score": "Score выше твоего порога: {value}",
        "compare_filter_volume": "Объём выше твоего порога: {value}",
        "compare_filter_direction": "Направление совпало с фильтром: {value}",
        "compare_filter_watchlist": "Сигнал попал в твой текущий список монет",
        "compare_filter_gold": "Золото включено в твоём потоке",
        "compare_change_score_up": "Score выше на {value}",
        "compare_change_score_down": "Score ниже на {value}",
        "compare_change_score_flat": "Score без изменений",
        "compare_change_rsi": "RSI сместился с {previous} до {current}",
        "compare_change_volume_up": "24ч объём стал сильнее",
        "compare_change_volume_down": "24ч объём стал слабее",
        "compare_change_volume_flat": "24ч объём почти без изменений",
        "compare_change_timeframe": "Таймфрейм изменился с {previous} на {current}",
        "compare_change_direction": "Направление изменилось с {previous} на {current}",
    },
}


def premium_text(language: str | None, key: str, **kwargs: object) -> str:
    normalized = normalize_language(language)
    template = _TEXTS.get(normalized, {}).get(key) or _TEXTS["en"][key]
    if kwargs:
        return template.format(**kwargs)
    return template


_TEXTS["en"].update(
    {
        "menu_watchlists": "👀 Watchlist",
        "menu_delivery": "🔔 Notifications",
        "menu_stats": "📊 Results",
        "menu_setup_wizard": "🪄 Wizard",
        "menu_daily_recap": "📅 Daily",
        "menu_weekly_recap": "🗓 Weekly",
        "menu_themes": "🎨 Themes",
        "menu_save_theme": "💾 Save Set",
        "menu_add_to_theme": "➕ Add Symbols",
        "menu_rename_theme": "✏️ Rename",
        "menu_delete_theme": "🗑 Delete",
        "menu_resume_now": "🔔 Resume",
        "menu_open_strongest": "💥 Strong Setups",
        "menu_gold_card": "🥇 XAUUSD Card",
        "menu_gold_alerts_on": "🥇 Gold: On",
        "menu_gold_alerts_off": "🥇 Gold: Off",
        "delivery_mode_instant": "⚡ Instant",
        "delivery_mode_digest": "🗂 Digest",
        "delivery_mode_quiet": "🌙 Quiet",
        "snooze_1h": "😴 1h",
        "snooze_8h": "😴 8h",
        "snooze_tomorrow": "🌅 Until Morning",
        "snooze_today": "🌙 Until Tonight",
        "quiet_hours_off": "🌙 Off",
        "quiet_hours_late": "🌙 Late",
        "quiet_hours_overnight": "🌙 Overnight",
        "watchlists_title": "Watchlist",
        "watchlists_themes_title": "Themes",
    }
)

_TEXTS["ru"]["compare_empty"] = "Исходная точка не сохранилась. На новых уведомлениях кнопка покажет, что изменилось с момента входа."

_TEXTS["ru"].update(
    {
        "menu_watchlists": "👀 Вотчлист",
        "menu_delivery": "🔔 Уведомления",
        "menu_stats": "📊 Результаты",
        "menu_setup_wizard": "🪄 Мастер",
        "menu_daily_recap": "📅 День",
        "menu_weekly_recap": "🗓 Неделя",
        "menu_themes": "🎨 Темы",
        "menu_save_theme": "💾 Сохранить набор",
        "menu_add_to_theme": "➕ Добавить тикеры",
        "menu_rename_theme": "✏️ Переименовать",
        "menu_delete_theme": "🗑 Удалить",
        "menu_resume_now": "🔔 Возобновить",
        "menu_open_strongest": "💥 Сильные сетапы",
        "menu_gold_card": "🥇 Карточка XAUUSD",
        "menu_gold_alerts_on": "🥇 Золото: Вкл",
        "menu_gold_alerts_off": "🥇 Золото: Выкл",
        "delivery_mode_instant": "⚡ Сразу",
        "delivery_mode_digest": "🗂 Дайджест",
        "delivery_mode_quiet": "🌙 Тихо",
        "snooze_1h": "😴 1ч",
        "snooze_8h": "😴 8ч",
        "snooze_tomorrow": "🌅 До утра",
        "snooze_today": "🌙 До вечера",
        "quiet_hours_off": "🌙 Выкл",
        "quiet_hours_late": "🌙 Поздние",
        "quiet_hours_overnight": "🌙 Ночные",
        "watchlists_title": "Вотчлист",
        "watchlists_themes_title": "Темы",
    }
)
