from __future__ import annotations

DEFAULT_LANGUAGE = "en"
SUPPORTED_LANGUAGES = ("en", "ru")

_TEXTS: dict[str, dict[str, str]] = {
    "en": {
        "language_name": "English",
        "language_switch_to": "Russian",
        "menu_alerts_on": "Alerts: ON",
        "menu_alerts_off": "Alerts: OFF",
        "menu_followups_on": "Follow-ups: ON",
        "menu_followups_off": "Follow-ups: OFF",
        "menu_signal_setup": "🎯 Filters",
        "classic_menu_signals": "📡 Signals",
        "classic_menu_setup": "🎯 Setup",
        "classic_menu_premium": "💎 Premium",
        "menu_back": "← Back",
        "menu_watchlist": "👀 Watchlist",
        "menu_current_watchlist": "👀 Current",
        "menu_latest_signals": "Fresh Signals",
        "menu_analyze_symbol": "🔎 Analyze",
        "menu_gold_snapshot": "🪙 Gold / XAUUSD",
        "menu_ai_analysis": "AI Analysis",
        "menu_market_status": "🟢 Bot Status",
        "menu_my_access": "💎 My Access",
        "menu_language": "Language: {language}",
        "menu_change_language": "🌐 Language",
        "menu_try_pro": "💳 Go PRO+",
        "menu_continue_pro": "💳 Pay PRO+",
        "menu_pay_pro": "💳 Pay PRO+",
        "menu_renew_pro": "💳 Renew PRO+",
        "menu_results_channel": "Results",
        "menu_public_channel": "Public Channel",
        "menu_community_chat": "Community",
        "menu_referral": "🎁 Referral",
        "menu_help": "❓ Help",
        "menu_hide": "Hide Menu",
        "menu_open": "Open Menu",
        "menu_home": "🏠 Home",
        "quick_links": "Quick links:",
        "channels_folder": "Join All Channels",
        "open_bot": "Open Bot",
        "open_pro_bot": "Open PRO+",
        "renew_now": "Renew now",
        "open_pro": "Open PRO+",
        "setup_conservative": "🛡 Conservative",
        "setup_balanced": "⚖ Balanced",
        "setup_aggressive": "⚡ Aggressive",
        "setup_rsi_tight": "27/73 Tight",
        "setup_rsi_balanced": "30/70 Balanced",
        "setup_rsi_early": "33/67 Early",
        "setup_both": "↕ Both",
        "setup_long_only": "🟢 Long",
        "setup_short_only": "🔴 Short",
        "setup_all_symbols": "🌍 All",
        "setup_watchlist_only": "⭐ Favorites Only",
        "setup_set_only": "🎯 Set",
        "setup_choose_set": "Choose Set",
        "setup_gold_alerts": "Gold: {state}",
        "setup_open_watchlist": "Favorites",
        "setup_custom": "✨ Custom",
        "setup_reset_to_base": "↺ Reset to Base",
        "custom_back_to_filters": "↩ Back to Filters",
        "signals_latest_tab": "Latest",
        "signals_strongest_tab": "Strongest",
        "watchlist_remove": "Remove",
        "copy_symbol": "Copy {symbol}",
        "open_binance": "Open in Browser",
        "open_binance_app": "Open in App",
        "open_binance_quick": "Binance + Copy",
        "open_tradingview": "TradingView",
        "open_gold_chart": "Open XAUUSD in TradingView",
        "button_ai_analysis": "AI Analysis",
        "button_risk_management": "Risk Management",
        "button_signal_reason": "Signal Reason",
        "button_delete": "Delete",
        "status_enabled": "enabled",
        "status_disabled": "disabled",
        "status_on": "ON",
        "status_off": "OFF",
        "status_admin": "Admin",
        "status_paid": "Paid",
        "status_trial": "Trial",
        "status_expired": "Expired",
        "status_free": "Free",
        "watchlist_empty": "empty",
        "watchlist_count": "{count} symbols",
        "watchlist_count_only": "{count} symbols (favorites only)",
        "language_switched": "Language switched to {target_language}.",
        "language_picker_welcome_title": "Choose Your Language",
        "language_picker_welcome_body": "Pick the language for menus, alerts, and buttons before you open the bot.",
        "language_picker_premium_body": "Syndicate PRO+ scans the crypto market, filters setups, and explains the signal context. Choose your interface language.",
        "language_picker_settings_title": "Language",
        "language_picker_settings_body": "Choose which language the bot should use for menus, alerts, and onboarding.",
        "language_picker_hint": "You can change it again anytime from Settings.",
        "language_picker_back": "Back to Settings",
        "language_picker_applied": "Language updated.",
        "language_selected_confirmation": "Language selected: {language_name}\n\nYour guided PRO+ start is below.",
        "classic_language_selected_confirmation": "Language selected: {language_name}\n\nYour Classic start is below.",
        "unknown_action": "Unknown action.",
        "symbol_not_recognized": "Symbol not recognized. Try BTC, BTCUSDT, BTC/USDT, BTC-PERP, or 1000PEPEUSDT.",
        "symbol_not_recognized_analyze": "Symbol not recognized. Try /analyze BTC, /analyze BTC-PERP 1h, /analyze BTC/USDT, or /analyze 1000PEPEUSDT.",
        "watchlist_full": "Your favorites are full. Keep it within {limit} symbols for clean bot UX.",
        "watchlist_added": "{symbol} added to favorites.",
        "watchlist_exists": "{symbol} is already in favorites.",
        "watchlist_removed": "{symbol} removed from favorites.",
        "watchlist_missing": "{symbol} was not in favorites.",
        "symbol_unavailable": "That symbol is not available in the current market universe.",
        "symbol_card_failed": "Unable to prepare that symbol card right now. Try again in a moment.",
        "menu_hint_private": "Use /menu for the main controls, open Signal Filters, or send a ticker like BTC / ETH 1h.",
        "menu_hint_classic": "Use /menu for Classic controls, open Signal Filters, or send a ticker like BTC / ETH 1h.",
        "callback_opening_setup": "Opening setup...",
        "callback_opening_watchlist": "Opening favorites...",
        "callback_opening_access": "Opening access...",
        "callback_opening_referral": "Opening referral...",
        "callback_opening_analyze": "How to analyze symbols...",
        "callback_opening_gold": "Loading gold...",
        "callback_opening_custom": "Opening custom setup...",
        "callback_preparing_renewal": "Preparing renewal...",
        "callback_premium_required": "Premium access is required.",
        "callback_refreshing_list": "Refreshing list...",
        "callback_opening_signal": "Opening setup...",
        "callback_profile_updated": "Profile updated.",
        "callback_profile_reset": "Base profile restored.",
        "callback_rsi_updated": "RSI setup updated.",
        "callback_volume_updated": "Volume floor updated.",
        "callback_direction_updated": "Direction filter updated.",
        "callback_universe_updated": "Universe updated.",
        "callback_choose_set": "Choose a set first.",
        "callback_gold_updated": "Gold preference updated.",
        "callback_removed_watchlist": "Removed from favorites.",
        "callback_watchlist_missing": "Symbol was not in favorites.",
        "callback_custom_cancelled": "Custom setup cancelled.",
        "callback_done": "Done.",
        "menu_reopened": "Main menu reopened.",
        "menu_updated": "Main menu updated.",
        "menu_collapsed": "Menu collapsed. Tap Open Menu or use /menu whenever you want the full controls back.",
        "results_channel_message": "Results / proof channel: {target}",
        "public_channel_message": "Public channel: {target}",
        "community_not_configured": "Community link is not configured yet.",
        "community_chat": "Community chat:",
        "no_strong_ai_pick": "No strong crypto setup is available for AI analysis right now.",
        "loading_ai_title": "Preparing AI analysis",
        "loading_ai_subtitle": "Pulling the strongest current setup and premium context",
        "loading_manual_ai_title": "Analyzing {symbol}",
        "loading_manual_ai_subtitle": "Building the premium AI card for this {timeframe} futures pair",
        "loading_symbol_title": "Loading {symbol}",
        "loading_symbol_subtitle": "Building a fresh {timeframe} snapshot with your filters",
        "loading_signals_title": "Loading signals",
        "loading_signals_subtitle": "Preparing the latest cards that match your current setup",
        "loading_signal_card_subtitle": "Opening the saved {timeframe} setup card",
        "ai_pick_failed": "Unable to prepare AI analysis right now. Try again in a moment.",
        "signals_delivery_failed": "Unable to load the latest signal cards right now. Try again in a moment.",
        "watchlist_only_empty": "Tracking-only mode is enabled, but the selected favorites or set is empty. Open Favorites or Sets and add a few tickers first.",
        "signals_title_latest": "Latest Signals",
        "signals_title_strong": "Strongest Setups",
        "signals_summary_all": "These setups already match your current filters.",
        "signals_summary_watchlist": "These setups match your favorites-only delivery mode.",
        "alerts_disabled_global": "Direct private alerts are disabled globally right now.",
        "alerts_state_changed": "Direct private alerts are now {state}.",
        "followups_state_changed": "Private follow-up delivery is now {state}.",
        "gold_state_changed": "Gold alerts are now {state} in the premium bot.",
        "classic_alerts_disabled_global": "Classic alerts are disabled globally right now.",
        "classic_alerts_state_changed": "Classic alerts are now {state}. They arrive about {delay_minutes} minutes later than the premium bot.",
        "classic_followups_state_changed": "Classic follow-up delivery is now {state}.",
        "payments_classic_only": "Payments are handled inside Syndicate PRO+.",
        "admin_access_active": "Admin access is already active. No payment is needed here.",
        "trial_active_now": "✅ Your PRO+ trial is active.\n\nEverything in the premium bot stays unlocked until the trial ends.",
        "paid_active_now": "✅ PRO+ is already active on this account.",
        "invoice_already_paid": "This invoice is already paid. PRO+ should already be active here.",
        "payment_setup_not_ready": "Payment setup is not ready yet. Try again in a moment.",
        "payment_link_failed": "Unable to prepare the payment link right now. Try again in a moment.",
        "payment_link_not_ready": "The payment link is not ready yet. Try again in a moment.",
        "payment_continue": "<b>💳 Continue with PRO+</b>\n\nUse the button below to unlock premium access again.",
        "payment_renew_title": "<b>🔁 Renew PRO+</b>\n\nYour current access stays active.\nThis payment simply adds another billing cycle.",
        "payment_offer_message": "<b>💳 PRO+ is paused</b>\n\nUnlock it again to restore:\n• earlier signals\n• AI analysis and risk cards\n• follow-ups and deeper context",
        "premium_feature_included": "<b>✅ {feature_name} is already included in your {access_label}</b>\n\nYour premium access is active.\nIf this card did not open, try again from the latest alert.",
        "premium_feature_locked": "<b>🔒 {feature_name} is part of Syndicate PRO+</b>\n\nThis feature lives in the private premium flow.\nIf your trial already ended, use the payment button below.\nIf the trial is still active, access opens automatically.",
        "access_status_admin": "Status: admin access",
        "access_status_free": "Status: free access",
        "access_trial_ends": "Trial ends: {timestamp} ({relative})",
        "access_paid_until": "Paid until: {timestamp} ({relative})",
        "access_expired": "Expired: {timestamp}",
        "relative_ended": "ended",
        "relative_in_days": "in {days}d {hours}h",
        "relative_in_hours": "in {hours}h {minutes:02d}m",
        "relative_in_minutes": "in {minutes}m",
        "profile_conservative": "Conservative",
        "profile_balanced": "Balanced",
        "profile_aggressive": "Aggressive",
        "profile_custom": "Custom",
        "rsi_mode_tight": "Tight",
        "rsi_mode_balanced": "Balanced",
        "rsi_mode_early": "Early",
        "rsi_mode_custom": "Custom",
        "direction_both": "Both sides",
        "direction_long": "Long only",
        "direction_short": "Short only",
        "threshold_context_oversold": "RSI is below {oversold} on the {timeframe} chart, which can point to short-term downside exhaustion. That still needs confirmation from price response and follow-through.",
        "threshold_context_overbought": "RSI is above {overbought} on the {timeframe} chart, which can point to short-term upside exhaustion. That still needs confirmation from price structure, not just the oscillator.",
        "threshold_context_neutral": "RSI is back inside your {oversold}/{overbought} window on the {timeframe} chart. This is watchlist context, not a clean extreme by your current setup.",
        "last_signal_none": "None yet",
        "last_signal_followup": "{symbol} ({stage} follow-up) - {timestamp}",
        "last_signal_alert": "{symbol} - {timestamp}",
        "interactive_stale": "This action is no longer available.",
        "interactive_not_interactive": "This alert is no longer interactive.",
        "interactive_state_stale": "This alert state looks stale. Try the latest card.",
        "interactive_disabled": "Interactive alerts are disabled here.",
        "interactive_private_inactive": "This private card is no longer active without PRO+.",
        "interactive_unsupported_tf": "Unsupported timeframe.",
        "interactive_refreshing": "Refreshing {timeframe}...",
        "interactive_updating": "Updating to {timeframe}...",
        "interactive_ai_locked": "AI Analysis is available in the premium bot.",
        "interactive_ai_preparing": "Preparing analysis...",
        "interactive_ai_loading_title": "Preparing AI analysis",
        "interactive_ai_loading_subtitle": "Pulling signal context and market structure",
        "interactive_ai_failed": "Unable to prepare AI analysis right now. Try again in a moment.",
        "interactive_risk_locked": "Risk Management is available in the premium bot.",
        "interactive_risk_preparing": "Preparing risk card...",
        "interactive_risk_loading_title": "Preparing risk management",
        "interactive_risk_loading_subtitle": "Calculating stops, targets, and R/R options",
        "interactive_risk_failed": "Unable to prepare risk management right now.",
        "interactive_reason_locked": "Signal Reason is available in the premium bot.",
        "interactive_reason_preparing": "Preparing signal rationale...",
        "interactive_reason_loading_title": "Preparing signal reason",
        "interactive_reason_loading_subtitle": "Reviewing the factors behind this trigger",
        "interactive_reason_failed": "Unable to prepare signal rationale right now.",
        "interactive_deleting": "Deleting...",
        "interactive_upgrade_title": "<b>🔒 {feature_name} is available in the premium bot</b>",
        "interactive_upgrade_body": "This detail card belongs to the private premium flow.",
        "interactive_upgrade_trial": "🎁 New users get a {days}-day trial.",
        "interactive_upgrade_cta": "Open the private bot to get the full alert analysis without delay.",
        "interactive_upgrade_button": "Open Premium Bot",
        "referral_open_link": "Open Link",
        "referral_share_link": "Share Link",
        "referral_refresh": "Refresh",
    },
    "ru": {
        "language_name": "Русский",
        "language_switch_to": "English",
        "menu_alerts_on": "Сигналы: ВКЛ",
        "menu_alerts_off": "Сигналы: ВЫКЛ",
        "menu_followups_on": "Фоллоу-апы: ВКЛ",
        "menu_followups_off": "Фоллоу-апы: ВЫКЛ",
        "menu_signal_setup": "Фильтры сигналов",
        "menu_back": "← Назад",
        "menu_watchlist": "Избранные",
        "menu_current_watchlist": "Открыть избранные",
        "menu_latest_signals": "Свежие сигналы",
        "menu_analyze_symbol": "AI анализ монеты",
        "menu_gold_snapshot": "🪙 Золото / XAUUSD",
        "menu_ai_analysis": "AI Анализ",
        "menu_market_status": "Статус бота",
        "menu_my_access": "Мой доступ",
        "menu_language": "Язык: {language}",
        "menu_change_language": "Сменить язык",
        "menu_try_pro": "💳 Перейти в PRO+",
        "menu_continue_pro": "💳 Оплатить PRO+",
        "menu_pay_pro": "💳 Оплатить PRO+",
        "menu_renew_pro": "💳 Продлить PRO+",
        "menu_results_channel": "Результаты",
        "menu_public_channel": "Публичный канал",
        "menu_community_chat": "Сообщество",
        "menu_referral": "Рефералы",
        "menu_help": "Помощь",
        "menu_hide": "Скрыть меню",
        "menu_open": "Открыть меню",
        "menu_home": "Главное меню",
        "quick_links": "Быстрые ссылки:",
        "channels_folder": "Подключить все каналы",
        "open_bot": "Открыть бота",
        "open_pro_bot": "Открыть PRO+",
        "renew_now": "Продлить сейчас",
        "open_pro": "Открыть PRO+",
        "setup_conservative": "🛡 Спокойно",
        "setup_balanced": "⚖ Баланс",
        "setup_aggressive": "⚡ Агрессивно",
        "setup_rsi_tight": "27/73 Жестко",
        "setup_rsi_balanced": "30/70 Баланс",
        "setup_rsi_early": "33/67 Рано",
        "setup_both": "↕ Оба",
        "setup_long_only": "🟢 Лонг",
        "setup_short_only": "🔴 Шорт",
        "setup_all_symbols": "🌍 Все",
        "setup_watchlist_only": "⭐ Только избранные",
        "setup_set_only": "🎯 Набор",
        "setup_choose_set": "Выбрать набор",
        "setup_gold_alerts": "Золото: {state}",
        "setup_open_watchlist": "Избранные",
        "setup_custom": "✨ Кастомное",
        "setup_reset_to_base": "↺ Сброс к базе",
        "custom_back_to_filters": "↩ К фильтрам",
        "signals_latest_tab": "Последние",
        "signals_strongest_tab": "Сильные",
        "watchlist_remove": "Убрать",
        "copy_symbol": "Скопировать {symbol}",
        "open_binance": "Открыть в браузере",
        "open_binance_app": "Открыть в приложении",
        "open_binance_quick": "Binance + копия",
        "open_tradingview": "TradingView",
        "open_gold_chart": "Открыть XAUUSD в TradingView",
        "button_ai_analysis": "AI Анализ",
        "button_risk_management": "Риск-менеджмент",
        "button_signal_reason": "Почему сигнал",
        "button_delete": "Удалить",
        "status_enabled": "включено",
        "status_disabled": "выключено",
        "status_on": "ВКЛ",
        "status_off": "ВЫКЛ",
        "status_admin": "Админ",
        "status_paid": "Оплачен",
        "status_trial": "Триал",
        "status_expired": "Истек",
        "status_free": "Бесплатно",
        "watchlist_empty": "пусто",
        "watchlist_count": "{count} тикеров",
        "watchlist_count_only": "{count} тикеров (только избранные)",
        "language_switched": "Язык переключен на {target_language}.",
        "language_picker_welcome_title": "Выбери язык",
        "language_picker_welcome_body": "Сразу выбери язык меню, алертов и кнопок, чтобы дальше бот открылся уже в нужной версии.",
        "language_picker_premium_body": "Syndicate PRO+ сканирует крипторынок, отбирает сетапы и объясняет контекст сигнала. Выбери язык интерфейса.",
        "language_picker_settings_title": "Язык",
        "language_picker_settings_body": "Выбери, на каком языке бот должен показывать меню, алерты и onboarding.",
        "language_picker_hint": "Поменять язык можно позже в настройках.",
        "language_picker_back": "Назад к настройкам",
        "language_picker_applied": "Язык обновлен.",
        "language_selected_confirmation": "Язык выбран: {language_name}\n\nНиже — короткий старт в PRO+.",
        "classic_language_selected_confirmation": "Язык выбран: {language_name}\n\nНиже — короткий старт в Syndicate Classic.",
        "unknown_action": "Неизвестное действие.",
        "symbol_not_recognized": "Тикер не распознан. Попробуй BTC, BTCUSDT, BTC/USDT, BTC-PERP или 1000PEPEUSDT.",
        "symbol_not_recognized_analyze": "Тикер не распознан. Попробуй /analyze BTC, /analyze BTC-PERP 1h, /analyze BTC/USDT или /analyze 1000PEPEUSDT.",
        "watchlist_full": "Избранное заполнено. Оставь не больше {limit} тикеров, чтобы бот работал аккуратно.",
        "watchlist_added": "{symbol} добавлен в избранные.",
        "watchlist_exists": "{symbol} уже есть в избранных.",
        "watchlist_removed": "{symbol} удален из избранных.",
        "watchlist_missing": "{symbol} не найден в избранных.",
        "symbol_unavailable": "Этот тикер сейчас недоступен в текущем рыночном списке.",
        "symbol_card_failed": "Не удалось подготовить карточку по этому тикеру. Попробуй еще раз чуть позже.",
        "menu_hint_private": "Используй /menu для основных действий, открой фильтры сигналов или просто отправь тикер, например BTC или ETH 1h.",
        "menu_hint_classic": "Используй /menu для Classic-управления, открой фильтры сигналов или просто отправь тикер, например BTC или ETH 1h.",
        "callback_opening_setup": "Открываю настройки...",
        "callback_opening_watchlist": "Открываю избранные...",
        "callback_opening_access": "Открываю доступ...",
        "callback_opening_referral": "Открываю рефералы...",
        "callback_opening_analyze": "Как анализировать тикеры...",
        "callback_opening_gold": "Загружаю золото...",
        "callback_opening_custom": "Открываю кастомную настройку...",
        "callback_preparing_renewal": "Готовлю продление...",
        "callback_premium_required": "Нужен премиум-доступ.",
        "callback_refreshing_list": "Обновляю список...",
        "callback_opening_signal": "Открываю сетап...",
        "callback_profile_updated": "Профиль обновлен.",
        "callback_profile_reset": "Базовый профиль восстановлен.",
        "callback_rsi_updated": "RSI-настройка обновлена.",
        "callback_volume_updated": "Фильтр объема обновлен.",
        "callback_direction_updated": "Фильтр направления обновлен.",
        "callback_universe_updated": "Режим отбора обновлен.",
        "callback_choose_set": "Сначала выбери набор.",
        "callback_gold_updated": "Настройка золота обновлена.",
        "callback_removed_watchlist": "Удалено из избранных.",
        "callback_watchlist_missing": "Тикера не было в избранных.",
        "callback_custom_cancelled": "Кастомная настройка отменена.",
        "callback_done": "Готово.",
        "menu_reopened": "Главное меню снова открыто.",
        "menu_updated": "Главное меню обновлено.",
        "menu_collapsed": "Меню скрыто. Нажми Открыть меню или используй /menu, когда захочешь вернуть полный набор кнопок.",
        "results_channel_message": "Канал результатов: {target}",
        "public_channel_message": "Публичный канал: {target}",
        "community_not_configured": "Ссылка на сообщество еще не настроена.",
        "community_chat": "Чат сообщества:",
        "no_strong_ai_pick": "Сейчас нет сильного крипто-сетапа для AI анализа.",
        "loading_ai_title": "Готовлю AI анализ",
        "loading_ai_subtitle": "Подтягиваю самый сильный текущий сетап и премиум-контекст",
        "loading_manual_ai_title": "Анализирую {symbol}",
        "loading_manual_ai_subtitle": "Собираю premium AI-карточку для этой фьючерсной пары {timeframe}",
        "loading_symbol_title": "Загружаю {symbol}",
        "loading_symbol_subtitle": "Собираю свежий {timeframe} snapshot с твоими фильтрами",
        "loading_signals_title": "Загружаю сигналы",
        "loading_signals_subtitle": "Подготавливаю последние карточки под твои текущие фильтры",
        "loading_signal_card_subtitle": "Открываю сохранённую карточку сетапа {timeframe}",
        "ai_pick_failed": "Не удалось подготовить AI анализ. Попробуй еще раз чуть позже.",
        "signals_delivery_failed": "Не удалось загрузить последние карточки сигналов. Попробуй еще раз чуть позже.",
        "watchlist_only_empty": "Включен режим отслеживания только по списку, но выбранные избранные или набор пока пусты. Открой избранные или наборы и добавь несколько тикеров.",
        "signals_title_latest": "Последние сигналы",
        "signals_title_strong": "Самые сильные сетапы",
        "signals_summary_all": "Эти сетапы уже соответствуют твоим текущим фильтрам.",
        "signals_summary_watchlist": "Эти сетапы соответствуют режиму доставки только по избранным.",
        "alerts_disabled_global": "Прямые premium-алерты сейчас глобально выключены.",
        "alerts_state_changed": "Прямые premium-алерты теперь {state}.",
        "followups_state_changed": "Приватные follow-up уведомления теперь {state}.",
        "gold_state_changed": "Уведомления по золоту в premium-боте теперь {state}.",
        "classic_alerts_disabled_global": "Classic-алерты сейчас глобально выключены.",
        "classic_alerts_state_changed": "Classic-алерты теперь {state}. Они приходят примерно на {delay_minutes} минут позже premium-бота.",
        "classic_followups_state_changed": "Classic follow-up уведомления теперь {state}.",
        "payments_classic_only": "Оплата доступна внутри Syndicate PRO+.",
        "admin_access_active": "Админ-доступ уже активен. Оплата здесь не нужна.",
        "trial_active_now": "✅ Твой триал PRO+ активен.\n\nВсе функции premium-бота открыты до его окончания.",
        "paid_active_now": "✅ PRO+ уже активен на этом аккаунте.",
        "invoice_already_paid": "Этот инвойс уже оплачен. PRO+ уже должен быть активен.",
        "payment_setup_not_ready": "Платежная настройка пока не готова. Попробуй еще раз чуть позже.",
        "payment_link_failed": "Не удалось подготовить ссылку на оплату. Попробуй еще раз чуть позже.",
        "payment_link_not_ready": "Ссылка на оплату пока не готова. Попробуй еще раз чуть позже.",
        "payment_continue": "<b>💳 Продолжить с PRO+</b>\n\nИспользуй кнопку ниже, чтобы снова открыть premium-доступ.",
        "payment_renew_title": "<b>🔁 Продлить PRO+</b>\n\nТекущий доступ сохраняется.\nЭтот платеж просто добавляет новый период.",
        "payment_offer_message": "<b>💳 PRO+ сейчас на паузе</b>\n\nПосле оплаты снова откроются:\n• ранние сигналы\n• AI анализ и risk-карточки\n• follow-up и более глубокий контекст",
        "premium_feature_included": "<b>✅ {feature_name} уже входит в твой {access_label}</b>\n\nПремиум-доступ активен.\nЕсли карточка не открылась, попробуй еще раз из последнего сигнала.",
        "premium_feature_locked": "<b>🔒 {feature_name} входит в Syndicate PRO+</b>\n\nЭта функция доступна в приватном premium-потоке.\nЕсли триал уже закончился, используй кнопку оплаты ниже.\nЕсли триал еще активен, доступ откроется автоматически.",
        "access_status_admin": "Статус: доступ администратора",
        "access_status_free": "Статус: бесплатный доступ",
        "access_trial_ends": "Триал до: {timestamp} ({relative})",
        "access_paid_until": "Оплачено до: {timestamp} ({relative})",
        "access_expired": "Истек: {timestamp}",
        "relative_ended": "завершено",
        "relative_in_days": "через {days}д {hours}ч",
        "relative_in_hours": "через {hours}ч {minutes:02d}м",
        "relative_in_minutes": "через {minutes}м",
        "profile_conservative": "Консервативный",
        "profile_balanced": "Сбалансированный",
        "profile_aggressive": "Агрессивный",
        "profile_custom": "Кастомный",
        "rsi_mode_tight": "Жесткий",
        "rsi_mode_balanced": "Сбалансированный",
        "rsi_mode_early": "Ранний",
        "rsi_mode_custom": "Кастомный",
        "direction_both": "Обе стороны",
        "direction_long": "Только лонг",
        "direction_short": "Только шорт",
        "threshold_context_oversold": "RSI ниже {oversold} на графике {timeframe}, что может указывать на краткосрочное истощение снижения. Но это все еще требует подтверждения по цене и продолжению реакции.",
        "threshold_context_overbought": "RSI выше {overbought} на графике {timeframe}, что может указывать на краткосрочное истощение роста. Но это все еще требует подтверждения по структуре цены, а не только по осциллятору.",
        "threshold_context_neutral": "RSI вернулся внутрь твоего окна {oversold}/{overbought} на графике {timeframe}. Это скорее watchlist-контекст, а не чистый экстремум по твоим настройкам.",
        "last_signal_none": "Пока нет",
        "last_signal_followup": "{symbol} ({stage} follow-up) - {timestamp}",
        "last_signal_alert": "{symbol} - {timestamp}",
        "interactive_stale": "Это действие больше недоступно.",
        "interactive_not_interactive": "Этот алерт больше не интерактивный.",
        "interactive_state_stale": "Состояние этого алерта устарело. Попробуй открыть последнюю карточку.",
        "interactive_disabled": "Интерактивные алерты здесь отключены.",
        "interactive_private_inactive": "Эта приватная карточка больше недоступна без PRO+.",
        "interactive_unsupported_tf": "Этот таймфрейм не поддерживается.",
        "interactive_refreshing": "Обновляю {timeframe}...",
        "interactive_updating": "Переключаю на {timeframe}...",
        "interactive_ai_locked": "AI Analysis доступен в premium-боте.",
        "interactive_ai_preparing": "Готовлю анализ...",
        "interactive_ai_loading_title": "Готовлю AI анализ",
        "interactive_ai_loading_subtitle": "Подтягиваю контекст сигнала и структуру рынка",
        "interactive_ai_failed": "Не удалось подготовить AI анализ. Попробуй еще раз чуть позже.",
        "interactive_risk_locked": "Risk Management доступен в premium-боте.",
        "interactive_risk_preparing": "Готовлю risk-карточку...",
        "interactive_risk_loading_title": "Готовлю risk management",
        "interactive_risk_loading_subtitle": "Считаю стопы, цели и варианты R/R",
        "interactive_risk_failed": "Не удалось подготовить risk management.",
        "interactive_reason_locked": "Signal Reason доступен в premium-боте.",
        "interactive_reason_preparing": "Готовлю логику сигнала...",
        "interactive_reason_loading_title": "Готовлю причину сигнала",
        "interactive_reason_loading_subtitle": "Проверяю факторы, из-за которых появился этот триггер",
        "interactive_reason_failed": "Не удалось подготовить объяснение сигнала.",
        "interactive_deleting": "Удаляю...",
        "interactive_upgrade_title": "<b>🔒 {feature_name} доступен в premium-боте</b>",
        "interactive_upgrade_body": "Эта детальная карточка относится к приватному premium-потоку.",
        "interactive_upgrade_trial": "🎁 Новым пользователям доступен {days}-дневный триал.",
        "interactive_upgrade_cta": "Открой приватный бот, чтобы получить полный разбор сигнала без задержки.",
        "interactive_upgrade_button": "Открыть Premium Bot",
        "referral_open_link": "Открыть ссылку",
        "referral_share_link": "Поделиться",
        "referral_refresh": "Обновить",
    },
}


def normalize_language(value: str | None) -> str:
    normalized = str(value or DEFAULT_LANGUAGE).strip().lower()
    if normalized.startswith("ru"):
        return "ru"
    return DEFAULT_LANGUAGE


def toggle_language(language: str | None) -> str:
    return "ru" if normalize_language(language) == "en" else "en"


def is_russian(language: str | None) -> bool:
    return normalize_language(language) == "ru"


def ui_text(language: str | None, key: str, **kwargs: object) -> str:
    normalized = normalize_language(language)
    template = _TEXTS.get(normalized, {}).get(key) or _TEXTS[DEFAULT_LANGUAGE][key]
    if kwargs:
        return template.format(**kwargs)
    return template


_TEXTS["en"].update(
    {
        "menu_signal_setup": "🎯 Filters",
        "menu_back": "◀️ Back",
        "menu_watchlist": "👀 Watchlist",
        "menu_current_watchlist": "👀 Current",
        "menu_analyze_symbol": "🔎 Analyze",
        "menu_market_status": "🟢 Bot Status",
        "menu_my_access": "💎 My Access",
        "menu_change_language": "🌐 Language",
        "menu_referral": "🎁 Referral",
        "menu_help": "❓ Help",
        "menu_home": "🏠 Home",
        "watchlist_added": "{symbol} was added to your watchlist.",
        "watchlist_exists": "{symbol} is already in your watchlist.",
        "watchlist_removed": "{symbol} was removed from your watchlist.",
        "watchlist_missing": "{symbol} is not in your watchlist.",
        "callback_opening_watchlist": "Opening your watchlist...",
        "callback_opening_analyze": "Opening AI Desk...",
        "watchlist_only_empty": "Tracking-only mode is on, but your watchlist or active set is still empty. Add a few symbols first.",
    }
)

_TEXTS["ru"].update(
    {
        "menu_signal_setup": "🎯 Фильтры",
        "classic_menu_signals": "📡 Сигналы",
        "classic_menu_setup": "🎯 Настройка",
        "classic_menu_premium": "💎 Premium",
        "menu_back": "◀️ Назад",
        "menu_watchlist": "👀 Вотчлист",
        "menu_current_watchlist": "👀 Текущий",
        "menu_analyze_symbol": "🔎 Разбор",
        "menu_market_status": "🟢 Статус бота",
        "menu_my_access": "💎 Мой доступ",
        "menu_change_language": "🌐 Язык",
        "menu_referral": "🎁 Рефералы",
        "menu_help": "❓ Помощь",
        "menu_home": "🏠 Домой",
        "watchlist_added": "{symbol} добавлен в вотчлист.",
        "watchlist_exists": "{symbol} уже есть в вотчлисте.",
        "watchlist_removed": "{symbol} удалён из вотчлиста.",
        "watchlist_missing": "{symbol} нет в вотчлисте.",
        "callback_opening_watchlist": "Открываю вотчлист...",
        "callback_opening_analyze": "Открываю AI Desk...",
        "watchlist_only_empty": "Сейчас включён режим только по списку, но вотчлист или активный набор пока пусты. Добавь несколько тикеров.",
    }
)
